export default {
  REQUEST_GET_ME: 'REQUEST_GET_ME',
  REQUEST_GET_ME_SUCCESS: 'REQUEST_GET_ME_SUCCESS',
  REQUEST_GET_ME_ERROR: 'REQUEST_GET_ME_ERROR',

  REQUEST_SIGN_IN: 'REQUEST_SIGN_IN',
  REQUEST_SIGN_IN_SUCCESS: 'REQUEST_SIGN_IN_SUCCESS',
  REQUEST_SIGN_IN_ERROR: 'REQUEST_SIGN_IN_ERROR',
};
